version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: ${DOCKERFILE_BASE}
    image: base

  jupyter:
    build:
      context: .
      dockerfile: ${DOCKERFILE_JUPYTER}
    ports:
      - "8888:8888"
    volumes:
      - ${LOCAL_PROJECT_DIR}/jupyter:/workspace/jupyter
    env_file:
      - .env
