version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base.linux
      args:
        CUDA_VERSION: ${CUDA_VERSION}
        CUDNN_VERSION: ${CUDNN_VERSION}
    image: base
